print ('tipos primitivos')
n = input ('Digite algo: ')
print ('E um número?',n.isnumeric())
print ('Todas são letras?',n.isalpha())
print('Todas as caracteres são alfanumericos?',n.isalnum())
print('Estão em letra maiuscula? ',n.isupper())
print('Estão em letra minuscula?',n.islower())
print('É um Ascii?',n.isascii())
print ('Esta capitalizada?',n.istitle())
